### ISSUE TITLE
Mikado.compile (in browser) error if template contains elements without closing tag

### ISSUE THREAD

**Issue by moromindful** [nextapps-de/mikado#10]
If you have non closing elements in the template (br, img, input, etc.) calling the compile method throws: TypeError: Cannot read property 'nodeValue' of null

> const template = ( 

    `<template id="testnonclosing">
        <div>
			<h1>Test non closing</h1>
			<input name="firstname" type="text">
			<br>
			<br />
        </div>
        <div>
			<h1>Test non closing</h1>
                        <img src="" alt="">
                        <img src="" alt="" />
        </div>
    </template>`
);

*tested only in browser

**Comment by ts-thomas** [comment]
Thanks for this hint. That issue just happens when using runtime compiler. I will provide a fix for that very sool.

**Comment by ts-thomas** [comment]
This is now fixed in 0.6.15
