### ISSUE TITLE
Mikado.once doesn't work if provided a callback.

### ISSUE THREAD

**Issue by moromindful** [nextapps-de/mikado#11]
According to your example : Mikado.once(root, template, data, payload, callback);
We could provide a callback, but when providing a callback it will render after destroy(true) so it throws : 
Template was not mounted or root was not found.
Cannot read property '0' of null

**Comment by ts-thomas** [comment]
Thanks for this hint. It was not covered by the tests. So I will add this and provide a fix very soon.

**Comment by ts-thomas** [comment]
This was fixed in 0.6.14
