### ISSUE TITLE
src/mikado.js line 850 typo error

### ISSUE THREAD

**Issue by moromindful** [nextapps-de/mikado#12]
Hi, in src/mikado.js on line 850 we have this.apply(tmp, item, view, x) and should have been this.apply(tmp, item, x, view). Right now you are passing the payload instead of the index.

I also provided a comment on your commit at the specified line.

I am now in the learning phase of mikado. And still have a bunch of things to test and see how they would fit best in my future projects. Anyway you did an amazing job creating mikado. Congrats!

**Comment by ts-thomas** [comment]
Very well seen. Fixed in 0.6.12
