### ISSUE TITLE
update api docs

### ISSUE THREAD

**Issue by moromindful** [nextapps-de/mikado#13]
I think some api methods from docs (README.md) are out of sync with the code.

1 . view.init(\<template\>, \<options\>)
- template is not optional
- the example below will not work:
Initialize an existing view with new options:
view.init(options);

2 . view.apply(node, \<data\>, \<payload\>)
- the definition of method is: .apply = function(root, data, index, payload) and it is not handled so that it can check if payload is provided instead of index.
- there is no description for this method on where and how to use it.

3 . view.add(data, \<payload\>)
- the example below will not work:
Add one data item before an index:
view.add(data, 0); // add to beginning

4 . view.update(node, data, \<payload\>)
- it should of been view.update(node | index, data, \<payload\>), because it is handled if we provide a number instead of a node.

5 . view.refresh(\<payload\>)
- it should of been view.refresh(\<node | index\>,\<payload\>)

6 . view.shift(node | index, index), view.listen(event) and view.unlisten(event)
- there is no description for this methods on where and how to use it.

7 . Reactive Proxy (Observer) - version from Limitations needs to be updated 
- Proxy actually comes with some limitations on template expressions. Improving those restrictions is already work in progress and will release in v0.5.0.

**Comment by ts-thomas** [comment]
WOW really cool. Thanks a lot, I'll put the changes into the doc. Sorry for the incompleteness.

**Comment by ts-thomas** [comment]
All updated in v0.6.13
1 . template is now optional
2 . docs updated, this method should be private and is an internal shortcut for update, use update instead
3 . this is now supported, also .append(data, index) is now supported
4. docs updated
5. docs updated
6. docs updated
7. docs updated, this feature is still in draft

Thanks a lot again.

**Comment by FTOH** [comment]
___Mikado.new()___ was removed in 0.7.0
