### ISSUE TITLE
Typescript support [Question]

### ISSUE THREAD

**Issue by simoneromano96** [nextapps-de/mikado#14]
Hello, I've found this framework interesting, but I could not see if it supports typescript and how to create a typescript based mikado project.
Does mikado support typescript? How do I configure a mikado project with typescript? If it is not supported, is it in the roadmap?

Thanks

**Comment by s0kil** [comment]
We just need to add a TypeScript type definition file

**Comment by ts-thomas** [comment]
@s0kil could you basically create those file?

**Comment by s0kil** [comment]
@ts-thomas Yes, take a look at this repo dedicated to type definition files, https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chai-dom/index.d.ts

**Comment by cbbfcd** [comment]
@ts-thomas , @s0kil 
just try: https://github.com/microsoft/dts-gen

**Comment by ts-thomas** [comment]
A typescript definition files was added. It needs probably further improvement but provides a basic start.
