### ISSUE TITLE
click events don't work in IE10/11

### ISSUE THREAD

**Issue by moromindful** [nextapps-de/mikado#15]
In IE11 on a touchscreen device the click event is registered as a "tap"/touch event. And IE10/11 doesn't support touch events.

**Comment by ts-thomas** [comment]
Hello thanks for the report. This should be fixed in v0.6.42, the synthetic "tap" listener is now only used when explicitly assigning as `<div tap="handler">`. A support for MSIE PointerEvents for the synthetic listener will follow.

**Comment by ts-thomas** [comment]
PointerEvents are now supported in v0.6.5.
