### ISSUE TITLE
TodoMVC: Proper method for running the demo

### ISSUE THREAD

**Issue by ibsusu** [nextapps-de/mikado#16]
In order to make the todo app work after removing all files in the subdirectories of `./template` except for *.html files I had to:

1. `npm install mikado`
2. `npm install mikado-compile`
3.  At the root directory of `todomvc/` run the following - 
```bash
npx mikado-compile template/main/main.html
npx mikado-compile template/footer/footer.html
npx mikado-compile template/list/list.html
npx mikado-compile template/app/app.html
```
4. `npx http-server`

5. then go to `localhost:8080/` and interact with the site.

At step 3 I tried `npx mikado-compile`, `npx mikado-compile template`, and `npm run compile`.  None of them worked.

At step 4 I tried `npx mikado-server` and `npm run server`.  Neither of the commands worked.

I got it working so I'm happy, I'm just wondering if I'm supposed to do something else.  Cool project btw.

**Comment by s0kil** [comment]
@ts-thomas I could take care of this.

**Comment by ts-thomas** [comment]
This should be fixed now. The last update for the compiler module supports wildcards, you just need `npx mikado-compile template/*.html` to compile all html file within a folder as an example. Also you can pass a specific format e.g. `npx mikado-compile template/*.html es6` (this will export just the ES6 modules). I have to update the docs inside TodoMVC docs.

**Comment by ts-thomas** [comment]
I just pointed out, that I have to add flags for console commands, because my example from above will use the "es6" as destination root. So we need something like: `npx mikado-compile -src template/*.html -dest template/ -type es6` with corresponding shortcuts `npx mikado-compile -s template/*.html -d template/ -t es6`
