### ISSUE TITLE
Consider a community chat

### ISSUE THREAD

**Issue by s0kil** [nextapps-de/mikado#17]
@ts-thomas Could we set up a community chat for Mikado?
Slack, Gitter, etc

**Comment by simoneromano96** [comment]
Personally I'd suggest discord, I'm already using it for rust, go, flutter and for some cool projects like docker coder, svelte, quasar, azul and more

**Comment by ts-thomas** [comment]
In our company we use slack. I much like the possibilities of integrations. But thanks a lot for the suggestions, I will take a look into. The chat should be available at the end of this year, so we have some time :)

**Comment by ts-thomas** [comment]
I created a discord server "Mikado": https://discord.gg/GRgkYWv
