### ISSUE TITLE
Docs Website

### ISSUE THREAD

**Issue by s0kil** [nextapps-de/mikado#19]
It would be nice to have a docs website for easier way to browse the documentation.

We could generate the docs using [Docute](https://docute.org/), [Docsify](https://docsify.js.org/), etc and host with GitHub pages.

**Comment by s0kil** [comment]
I'm willing to submit PR.

**Comment by ts-thomas** [comment]
Very nice idea, a Website is already in draft made by our designer. The release is planned at 2020-01-01 😊

**Comment by ts-thomas** [comment]
It should be a surprise, so I need to close this issue :)
