### ISSUE TITLE
proxy {{= is not working anymore

### ISSUE THREAD

**Issue by moromindful** [nextapps-de/mikado#21]
I had a view setup with lose=true, store=true and the template contains only one {{= data.isloading }}. Now after the update when i change: view.data(0).isloading = 'is-loading'; the data is updated but the dom is not.

I tried with an external store, with an observable array array also. The observable array only works if I change the whole data object at index 0. But I need to change only one property ...

**Comment by ts-thomas** [comment]
Please post me the template, it might to something wrong there.

**Comment by ts-thomas** [comment]
And please make sure you did not use the light version :)

**Comment by moromindful** [comment]
I didn't use the light version. I use mikado.debug.js in a script tag in head. Also I compile the template in the browser from a string. I attached a template.
[template.txt](https://github.com/nextapps-de/mikado/files/3785085/template.txt)

the data which is passed to the view.render is: {"isloading":""}

Also I am using correctly with view.data(0).isloading = "is-loading" which should of added the is-loading class tot the button from the template.

**Comment by moromindful** [comment]
Something gets messed up because 
proxy_setter$$module$tmp$proxy[tmp[0]](path[tmp[1]], value, tmp[2] || prop); 
from
function proxy_loop$$module$tmp$proxy(handler, path, prop, value) 
never gets called because exp is undefined. I attached two printscreens from chrome dev tools.
![1](https://user-images.githubusercontent.com/18190486/67798666-9beee180-fa8c-11e9-9bef-7b76e1a6356b.png)
![2](https://user-images.githubusercontent.com/18190486/67798668-9c877800-fa8c-11e9-8a18-c3971b7305cb.png)

the first one shows the value being set. the second one should have reached proxy_setter but because exp is undefined it never calls that to update the dom.

**Comment by ts-thomas** [comment]
I found an issue with the compiler thanks to your report (fix is included in 0.7.44). But that doesn't solve the problem. Proxy actually are very limited (https://github.com/nextapps-de/mikado#limitations) and does not support concatenation of static and dynamic content within a property value.

Let me show you a simple example. That would work like expected:
```html
<div>
    <div class="{{= data.isloading }}"></div>
</div>
```

This not:
```html
<div>
    <div class="class_a class_b class_c {{= data.isloading }}"></div>
</div>
```

I will add support for this very soon. Proxy is a whole chapter and the concept is actually still in draft. In the meanwhile you could use no proxy:

```html
<div>
    <div class="class_a class_b class_c {{ data.isloading }}"></div>
</div>
```

just call `view.render(data)`. Here, concatenation of static and dynamic content are supported.

I wonder you was writing "is not working anymore" ... did this work before?

I saw some expressions like `{{ t(' ... ') }}` ... that could be an issue when `t` isn't defined (which I could not find). When you like you can pass a payload to the render, like:

```js
const payload = { f: function(key){ /* ... */ } };
view.render(data, payload);
```
This would make the method `f` available via the ___view___ identifier `{{ view.t('pagelogin.username') }}`. Same way you can bind any value to `f`;

**Comment by ts-thomas** [comment]
I don't know why this issue was closed, sorry

**Comment by moromindful** [comment]
I wonder you was writing "is not working anymore" ... did this work before?
I think was working :) ... I discovered that is not working when you introduced the observable array. I will download older versions, try them and let you know.

"I saw some expressions like {{ t(' ... ') }}" : t is a global/window function which handles translation.

"When you like you can pass a payload to the render" : I prefer to use an external state with functions that I use in every view/template for example a capitalize function. because the state is shared across all view instances.

**Comment by moromindful** [comment]
It wasn't working ... In the past i controlled the dom via mikado.toggleClass :) and then switched to {{= just as a test and never looked if it was working. 

"Let me show you a simple example. That would work like expected" : 
I understand now how I should use the proxy feature. Thank you.

**Comment by ts-thomas** [comment]
"I prefer to use an external state with functions"
yes that's fine, if you like to share a function to all view instances you can use the "state" for this purpose alternatively: https://github.com/nextapps-de/mikado#view.state

```js
const state = { t: window.t };
const view = Mikado(root, template, { state: state })
view.render(data);
```
every further view which is created will also has access to the same state (same reference).

Then the template expression looks like `{{ this.state.t('pagelogin.username') }}`. But it has just the advantage to avoid access to the global scope. When you just need one identifier (like "t") then it is totally fine when you simply call it directly within the template expression (like you do actually).
