### ISSUE TITLE
We need to handle XSS

### ISSUE THREAD

**Issue by ts-thomas** [nextapps-de/mikado#23]
I already made some notes to this topic: https://github.com/nextapps-de/mikado#xss-security

We should start by supporting an external sanitizer for the client side which could be passed as a parameter when initialize the view (not compiling, because this method is optional).

**Comment by ts-thomas** [comment]
Reference Sheet: https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)

**Comment by ts-thomas** [comment]
Luckily, this topic is not as large as I expected. We can reduce the problem to rendering contents which was made by an user input. This is generally covered by a sanitizer before storing data in the DB, but not all user inputs will make their way through the DB. At least we just need to provide a simple sanitizer for the client side (as long SSR isn't fully supported).

One suggestion is to handle those through the curly brackets.

Sanitized:
```html
<template>
<div>{{ data.query }}</div>
</template>
```

Not sanitized:
```html
<template>
<div>{ data.query }</div>
</template>
```

Another suggestion is to use an exclamation mark before brackets:
Sanitized:
```html
<template>
<div>!{{ data.query }}</div>
</template>
```

Not sanitized:
```html
<template>
<div>{{ data.query }}</div>
</template>
```

What would you prefer?

**Comment by s0kil** [comment]
`!{ data.null }`  What about switching to single brackets? It seems to me that double brackets are simply unnecessary.

**Comment by snshn** [comment]
I believe it's triple brackets in handlebars-like templating engines for un-sanitized, and double brackets for sanitized. Not sure how possible it would be to match their syntax, but not having to learn a new one would help reducing the learning curve.

**Comment by ts-thomas** [comment]
I will made some research about the common styles. I would also prefer something close to handlebars/mustache.

**Comment by snshn** [comment]
Make sure to take a look at what Meteor did with Spacebars (their fork of Handlebars). It was uber convenient. http://blazejs.org/api/spacebars.html

**Comment by ts-thomas** [comment]
Meteor is one of my favorite frameworks 😊

**Comment by ts-thomas** [comment]
3 curly brackets just indentifiy to insert contents as html, using a sanitizer is also just recommended by Meteor. All inserts via 2 curly brackets are automatically escaped when using Meteor also when using Mikado actually.

A very short explanation how I get to the Mikados template syntax:

In the draft phase of Mikado I took all common template languages and compared them accordingly to the goal "designer readable templates" which are also common known by developers. At the end just mustache and handlebars are left over. Also some W3C drafts has helped me to find a decision. Mustache and handlebars has "render blocks" (sections/groups), but there are some reason why Mikado doesn't support those render blocks. Because I also know some common templating libs from the server side (like pug/jade) and how their are implemented. Internally an include, a conditional or a loop is interpreted like an tag with attributes and its easy to provide deeply nested branches of different mixed logic. That isn't that easy when using open and closing virtual markups. It depends a lot of the compiler and how they parse the template. It was also a goal to provide a JSON-compatible format (for future SSR). So I ended with something like using handlebars/mustache as its base and providing special template expressions via tags and attributes (not virtual). Also there is a basic requirement coming from Mikados internal architecture (and its performance), every partial (looped/included/conditional) has to provide one root node as the outer bound. This technique is something new and also might be feel a bit limited, but basically that is where the performance starts. Things like `{{#list}} ... {{/list}}` wouldn't possible without side effects. In the past I used some libs which implicitly added custom root nodes in the DOM for this purpose (also inferno as I can remember), but that was something I would like to prevent. That's why Mikados templates has to provide the root node explicit. Also providing plain Javascript anywhere within the template and return them as content is pretty new but opens a new world of possibilities. Mikado templates don't uses "eval" and provides a real execution context. That all has influenced the final template syntax.

**Comment by snshn** [comment]
Thank you for explaining things in details. I'm thinking now that it could be beneficial to keep a table somewhere in the project's Wiki showing side-by-side comparison between different templating languages and Mikado, e.g. 

|        | Handlebars                                 | ... | ... | Mikado |
|--------|--------------------------------------------|-----|-----|--------|
| Loops  | {{#each array as |value key|}}...{{/each}} | ... | ... | ...    |
| If     | ...                                        | ... | ... | ...    |
| Unless | ...                                        | ... | ... | ...    |

That could help developers familiar with Handlebars/Mustache pick up Mikado's templating syntax easier, plus demonstrate what features Mikado lacks and what unique features it provides instead.

**Comment by snshn** [comment]
A bit off-topic, but also wanted to add that if currently Mikado has the best performance out of all templating engines, it might be a good idea to re-architect it in a way so that other templating engines could utilize it underneath (instead of using their own slow engines), while preserving their own syntax, and let libraries like Vue and Angular use Mikado's fast engine (included as na NPM module), but remaining compatible with their templating language's syntax.

**Comment by ts-thomas** [comment]
It depends on the template engine. Handlebars and mustache are non-functional full declarative template system. It just requires a new compiler for those syntax to fully archieve compatibilty. Other engines may less declarative and those ones requires an adapter additionally to get full compatibility. It does not need changing architecture.
