### ISSUE TITLE
README.md is too long

### ISSUE THREAD

**Issue by snshn** [nextapps-de/mikado#25]
I'd like to suggest breaking down everything from **Table of contents** down to the very bottom of the page into small(er) .md files, and putting them into `docs/`, possibly at some point generating a static website out of it to serve as a documentation.

**Comment by s0kil** [comment]
Rekated to #19

**Comment by ts-thomas** [comment]
Yes, along with the upcoming website it is planned to parse md or build them (actually not clear which of both), that will also split the documentation hierarchically.

**Comment by ts-thomas** [comment]
building the markdown files has some advantages, we will use well structured templates which could be exported to md.
