### ISSUE TITLE
Typos in README

### ISSUE THREAD

**Issue by rillig** [nextapps-de/mikado#29]
The word `thrust` should be `trust`.
The words `you are thrust` should be `you trust`.
The words `mode which boost` should be `mode, which boosts`.

**Comment by ts-thomas** [comment]
All done https://github.com/nextapps-de/mikado/pull/30
Thanks to @s0kil

**Comment by s0kil** [comment]
In README, this is not clear:

"When data is changed, the input elements will automatically update, as well as other turn around, when the input elements gets new data the store will automatically update."

https://github.com/nextapps-de/mikado/blob/master/README.md#L3211

What does this mean @ts-thomas ?
