### ISSUE TITLE
Using template in the same file with Mikado's constructor

### ISSUE THREAD

**Issue by vuhg** [nextapps-de/mikado#3]
Hi Thomas Wilkerling,

Any chance to use template as following and compile to json format with babel:
```js
const user = ...

const template = html`
<table>
    <tr>
        <td>User:</td>
        <td>${user}</td>
    </tr>
    <tr>
        <td>Tweets:</td>
        <td>${user.tweets.length}</td>
    </tr>
</table>
`

const view = Mikado.new(template);
```

**Comment by ts-thomas** [comment]
Actually this way is not possible. But you can compile the template and put the json into the sourcecode.

```js
const json = { /* template */ };
const view = Mikado.new(json);
```

I will think about to provide a runtime compiler as a fallback.

**Comment by vuhg** [comment]
> I will think about to provide a runtime compiler as a fallback.

Thank you, that would be great!

Is it posible to have webpack loader for `mikado` like vue or svelte?

```js
// component.mi
<div>{hello}</div>

<script>
const hello = 'Hello world!'
</script>

<style>
div {
  padding: 4px;
  font-size: 20px;
}
</style>
```

**Comment by ts-thomas** [comment]
That is a good suggestions, thanks. It will provide a loader very soon.

**Comment by ts-thomas** [comment]
Runtime compilation of templates are now supported (0.5.0).
Read more about here: https://github.com/nextapps-de/mikado#compiler
