### ISSUE TITLE
Shouldn't keyed test use key property?

### ISSUE THREAD

**Issue by pakastin** [nextapps-de/mikado#32]
Shouldn't the third value of `list` be `'id'` instead of `null` if it should be keyed test?
https://github.com/nextapps-de/mikado/blob/dfb701bb335f607951a60062e85918ebb984dd56/bench/test/redom/keyed.html#L66

**Comment by ts-thomas** [comment]
You are right. Thanks a lot for the hint.

**Comment by ts-thomas** [comment]
Update was deployed.
