### ISSUE TITLE
Add morphdom to benchmarks

### ISSUE THREAD

**Issue by s0kil** [nextapps-de/mikado#35]
It would be good to add https://github.com/patrick-steele-idem/morphdom to the Mikado benchmark, since both use a similar pattern of DOM patching.

**Comment by Dan-Do** [comment]
It's here, isn't it?
https://krausest.github.io/js-framework-benchmark/current.html

**Comment by s0kil** [comment]
@Dan-Do Mikado has it's own benchmark: https://github.com/nextapps-de/mikado/tree/master/bench

**Comment by ts-thomas** [comment]
The morphdom project isn't active anymore
