### ISSUE TITLE
Compiling the Todo demo fails

### ISSUE THREAD

**Issue by amartincolby** [nextapps-de/mikado#38]
Compiling the Todo demo fails because it's referencing mikado/task/compile instead of mikado-compile. The compile command in the package.json references the wrong path for the template files. Serve references task/server instead of the npm package for mikado-server.

**Comment by Dan-Do** [comment]
The todomvc demo uses the old versions too. If we use latest version, there is error:
`Uncaught TypeError: can't access property "hidden", self is undefined`

**Comment by Dan-Do** [comment]
FYI, the templates need to be re-compiled.
One more thing, we cannot open the file index.html directly in the browser, as the localStorage does not exist.

**Comment by ts-thomas** [comment]
Examples will come back soon
