### ISSUE TITLE
basic demo is missing data.js and template.js files

### ISSUE THREAD

**Issue by s0kil** [nextapps-de/mikado#4]
@ts-thomas Should I create those files based on [basic-example](https://github.com/nextapps-de/mikado#basic-example)?

**Comment by ts-thomas** [comment]
Ooops my fault, I forgot to add those files to the repo.

**Comment by ts-thomas** [comment]
Missing demo data files has been added: https://github.com/nextapps-de/mikado/tree/master/demo/basic
