### ISSUE TITLE
Renderer add div to text element

### ISSUE THREAD

**Issue by Dan-Do** [nextapps-de/mikado#40]
Template:
```html
<a href="/home"><i class="fa fa-home"></i> Oreo</a>
```
Rendered:
```html
<a href="/home"><i class="fa fa-home"></i><div>Oreo</div></a>
```
It makes the text show on another line which is not aligned with the fontawesome icon.

**Comment by ts-thomas** [comment]
In the documentation is was explained. The new version Mikado v0.8.x don't have this limitation anymore.
