### ISSUE TITLE
Issue when used together with Webpack?

### ISSUE THREAD

**Issue by mrft** [nextapps-de/mikado#43]
Hi
When trying to use Mikado inside a webpack-packaged application, I see the following error on the browser's console:
`Uncaught ReferenceError: SUPPORT_EVENTS is not defined`
which seems plausible since the first 3 lines of event.js seem to be
```
import Mikado from "./mikado.js";

if(SUPPORT_EVENTS){
```

It doesn't matter if I use `const Mikado = require('mikado');` or `import Mikado from 'mikado'`

Is this some sort of bug, or is it just me not understanding how this thing works or how it is supposed to be used?

**Comment by Dan-Do** [comment]
May be it's the problem after packaging. Please try with out webpack.

**Comment by mrft** [comment]
It works without webpack.

**Comment by ts-thomas** [comment]
Compiler flags was improved, they are imported by ES6 module loader. Also there are more versions available in the `dist` folder. Just pick one from there and don't use the `src ` folder, which needs a compilation which solves the compiler flags.
