### ISSUE TITLE
starting out with Mikado

### ISSUE THREAD

**Issue by AlidotSal** [nextapps-de/mikado#44]
I'm a newbie in using mikado (or any other ui library) and been trying to use it but I'm getting an empty page so far. 
what are the first steps to start using mikado ?

**Comment by ts-thomas** [comment]
I can recommend you to read the docs from the readme. Best is to start with this: https://github.com/nextapps-de/mikado#how-to-learn-mikado
You can find the final source code of this example on the bottom.
