### ISSUE TITLE
The docs state that we can refresh by node reference but the code that should handle it is commented out

### ISSUE THREAD

**Issue by agrinei** [nextapps-de/mikado#46]
In the docs / readme we have:

view.refresh(<node | index>, <payload>)

But the code snippet above, that should handle the node case is commented out:

        // else if(index && (typeof (tmp = index["_idx"]) === "number")){
        //
        //     node = index;
        //     index = tmp;
        // }

**Comment by ts-thomas** [comment]
`view.refresh` was removed in Mikado v0.8.x
