### ISSUE TITLE
The current reconcile algorithm will be slow in theory

### ISSUE THREAD

**Issue by yisar** [nextapps-de/mikado#47]
Because it's O (N ^ 2).

Theoretically, it is much slower than other algorithms, and the use case in performance test is just a special case of its speed.

**Comment by ts-thomas** [comment]
That is not true. Basically the loop looks like:

```js
for(x || (x = 0); x < max_end; x++){
    for(let y = x + 1; y < max_end; y++){
         // this isn't O (N ^ 2)
    }
}
```

Since `y` is starting from `x` this can't be O (N ^ 2)

**Comment by jonaszuberbuehler** [comment]
Check https://stackoverflow.com/questions/362059/what-is-the-big-o-of-a-nested-loop-where-number-of-iterations-in-the-inner-loop, seems like @yisar is right on this one.
