### ISSUE TITLE
Input max value in templates is removed when rendered

### ISSUE THREAD

**Issue by trevorjjacobs** [nextapps-de/mikado#52]
HTML provides a "max" attributed to set the maximum value for an input field. Mikado removes it when rendering the templates. This is most noticeable on range input fields because the max value determines how far a user can slide it to the right.

For example, I should be able to do this in the template...
<div><input id="qty-{{ data.id }}" type="range" value="{{ data.qty }}" max="{{ data.qtyMax }}"> </div>

But instead have to do this in the template...
<div><input id="qty-{{ data.id }}" type="range" value="{{ data.qty }}""> </div>
Then run this javascript after the template is rendered...
document.getElementById('qty-' + id).max = qtyMax;

The same issue applies to number input fields (e.g., "<input type="number" max="10") where it can be used for notifying users when they have entered a number outside of the range (e.g., "input:out-of-range { border: 2px solid red; }").

I think Mikado ignores the input max attribute because it is using the max attribute for loops.

**Comment by ts-thomas** [comment]
In Mikado 0.8.x this was renamed to `limit`, also can be used in combination with `offset`
