### ISSUE TITLE
Nesting views?

### ISSUE THREAD

**Issue by hsnoil** [nextapps-de/mikado#61]
Is there a best practice for nesting views? Or it should not be done unless the parent view is rendered as once?

**Comment by hsnoil** [comment]
> AFIK there is include property in the element template. Or there is embeded view.

Thanks, though how would I go about getting the child views if I do includes or is everything controlled by the top view? 

And is there documentation on the embeded views? Or do you simply mean add views manually? And then we have to also track deleting them manually too?

**Comment by Dan-Do** [comment]
Take a look at section "Loop Partials" in the readme, and todo app example.

**Comment by ts-thomas** [comment]
I will provide some examples soon, also how you could make "application view management" with Mikado
