### ISSUE TITLE
Any update?

### ISSUE THREAD

**Issue by zilveer** [nextapps-de/mikado#62]
Hi,
what a lovely library, it really kicks Svelte, Vue, React and even Vanilla when used properly.

But have I missed something about the progress?
I havent seen any progress for long time and I really hope the developer @ts-thomas keeps up the good work.

Well done and I am really looking forward to updates.

regards Zilveer

**Comment by ts-thomas** [comment]
Im glad to say that the new version is almost ready to publish. I will notice you when it is available.
Thanks a lot

**Comment by anoxxxy** [comment]
@zilveer @ts-thomas 

I must admit, I love Mikado also.

Regarding Mikado performance vs React, Vue and Svelte: Mikado outperforms all of them!

Keep it up @ts-thomas ! <3

**Comment by cayolblake** [comment]
@ts-thomas oh you gonna make a lot of people happy hearing this.

Any expected ETA?

**Comment by zilveer** [comment]
@ts-thomas when is Santa coming to deliver the new version ?
I think many here is eager o see it and waiting like a child waiting for Santa :) <3

**Comment by zilveer** [comment]
@ts-thomas Ho. I just wanna say heads up and hope everything is going well for you.

Please update us about the progress with Mikado.

Regards Zilveer

**Comment by ts-thomas** [comment]
A preview of the new version is now available and it is an improvement in every single aspect.
Thanks a lot
