### ISSUE TITLE
Issue with using templates with table tags

### ISSUE THREAD

**Issue by zilveer** [nextapps-de/mikado#63]
Hi,

I have issues with using templates with table tags.

This is my html:
```html
<table id="log"></table>
```

and this is my javascript
```javascript
var tweets = [
  {
    user: "User A",
    tweets: ["foo", "bar", "foobar"]
  },
  {
    user: "User B",
    tweets: ["foo", "bar", "foobar"]
  },
  {
    user: "User CC",
    tweets: ["foo", "bar", "foobar"]
  }
];

const tpl = 
  `<tr>
    <td>User: {{ data.user }}</td>
    <td>Tweets: {{ data.tweets.length }}</td>
  </tr>`;

const tplC = Mikado.compile(tpl);
const view = new Mikado(tplC);

const container = document.getElementById('log');
view.mount(container);

view.render(tweets)
```

But it throws error `Uncaught TypeError: can't access property "id", a is null`
on the line:  `const tplC = Mikado.compile(tpl);`

When I am using `div` tags in template it works good, but it doesnt want to work with `table` tags.
Can someone guide me here?

All help is appreciated.

regards Zilveer

**Comment by anoxxxy** [comment]
Hi,

you can solve it by making a small change in `mikado.debug.js` file. It will not break anything at all, it will just add suport for `child-to-parent` tags for nodes.

Change the line: `https://github.com/nextapps-de/mikado/blob/master/dist/mikado.debug.js#L2158`

to:
```javascript
var tagMapping = {
  td: "tr",
  tr: "tbody",
  li: "ul", // or "ol" for ordered list
  // Add more mappings as needed
};

var trimmedNode = node.trim();
var firstTag = trimmedNode.substring(trimmedNode.indexOf("<") + 1, trimmedNode.indexOf(">")).split(" ")[0];
var tmp = document.createElement(tagMapping[firstTag] || "div");
```

regards Anoxxxy

**Comment by ts-thomas** [comment]
The new version should fix that, but runtime compiler isn't available yet and btw also not suggested. Use the watcher from the new compiler to make things easier in development environments.
