### ISSUE TITLE
is it possible to use proxy with "{{#= ...}}" support?

### ISSUE THREAD

**Issue by zilveer** [nextapps-de/mikado#64]
Hi, 
I am using a template with only proxy brackets, but I am in need of passing HTML string also to the template, which looks like:

```html
<td data-sort="{{= data.inorders}}" data-balance="orders">{{#= data.inorders_format}}</td>
```

I set `store: true` when initiating Mikado., but when I check the console `store` is set to `false`.

I dont know if it is possible to use  proxy with HTML string support.
This is taken from the Advanced example
https://github.com/nextapps-de/mikado#advanced-example

It writes like this:
`To pass HTML markup as a string, the curly brackets needs to be followed by # e.g. {{# ... }}. For better performance, relevant tasks avoid passing HTML contents as a string.`

But it doesn't mention proxy support?
Thanks for any update on this.

Edit: If this isn't supported, I would love to see this feature in the coming update.
Edit2: I noticed that `stealth: true`, does that mean it runs in stealth mode with proxy for faster performance updates?

regards Zilveer

**Comment by ts-thomas** [comment]
Mikado v0.8.x is supporting `{{#= ... }}`

**Comment by ts-thomas** [comment]
The option `stealth` was renamed to `fullproxy`. It is a private property, which automatically enables, when every attribute on template expression has reactive bindings. Read here to get more about this topic: https://github.com/nextapps-de/mikado?tab=readme-ov-file#strict-proxy-mode
