### ISSUE TITLE
Mobile Benchmarks and Keyed Benchmarks

### ISSUE THREAD

**Issue by s0kil** [nextapps-de/mikado#7]
Since mobile performance is a large factor for some applications, here are some benchmarks.

## Device Details
![IMG_20190928_223859](https://user-images.githubusercontent.com/24403355/65825220-02c87300-e221-11e9-8435-cbfa50e95422.jpg)

## Android Power-Save Mode
![IMG_20190928_223917](https://user-images.githubusercontent.com/24403355/65825236-31464e00-e221-11e9-94e4-4ca92d266b93.jpg)

## Android Performance Mode
![IMG_20190928_224919](https://user-images.githubusercontent.com/24403355/65825249-48853b80-e221-11e9-95f5-7e014f79e5a6.jpg)

**Comment by ts-thomas** [comment]
Nice, thanks :)
I have recognized that the "toggle" test did not perform as expected. I fixed that in 0.4.22

**Comment by ts-thomas** [comment]
Safari (iOS 12.4.2)
![Bild von iOS](https://user-images.githubusercontent.com/12898005/66092628-fe87b700-e58c-11e9-88af-d0971d191172.png)

**Comment by s0kil** [comment]
@ts-thomas Any idea how `sinuous` achieves such repaint perf?

**Comment by ts-thomas** [comment]
These repaint benchmark of sinuous is pretty amazing, I need to step debug this to understand whats going on here :)

**Comment by ts-thomas** [comment]
Keyed Test
![raw githack com_nextapps-de_mikado_master_bench__keyed](https://user-images.githubusercontent.com/12898005/66163036-c71e1680-e62f-11e9-908c-bf1837535f5b.png)

**Comment by ts-thomas** [comment]
@s0kil whe need to make a new one, some of the libs has bypassed the whole test, so the old table was wrong.

https://github.com/nextapps-de/mikado#benchmark

**Comment by ts-thomas** [comment]
@s0kil the old test comes back. it is now named "data-driven" and its the 3rd test scenario along with "non-keyed" and "keyed". Luckily the repaint perf from sinuous had pointed out an issue with the test data and how it is cloned. As I fixed the test data the performance drops drastically for these libs. The new "data-driven" scenario test internal data changes and observer, so basically the old test environment is now back, also the old repaint perf from sinuous:

https://github.com/nextapps-de/mikado/blob/master/bench/README.md#data-driven-internal
