### ISSUE TITLE
When rendered a JS inline code Mikado returns `undefined`?

### ISSUE THREAD

**Issue by dominikkrulak** [nextapps-de/mikado#72]
I have this very simple template:

```
<div>
    {{@ const value = 'test'; }}
    <div>{{ value }}</div>
</div>
```

and when compiled and rendered It returns this:
```
<div>
    <div>undefined</div>
</div>
```

The compiled template contains an empty object literal which I think returns an `undefined` when rendered.

The start of compiled template:
```
export default{
name:"test",
tpl:{
  tag: "div",
  child: [
    {}, <-- this empty object literal seems like it came from JS inline code{{@ const value = 'test'; }}
    { ...
```

I'd like to ask if this behaviour is intentional?

**Comment by ts-thomas** [comment]
Thanks a lot for the error report. It was fixed in the latest version. Also it is now covered by this test:
https://github.com/nextapps-de/mikado/blob/master/test/browser/scope.js
template:
https://github.com/nextapps-de/mikado/blob/master/test/tpl/scope.html
