### ISSUE TITLE
Issues with loading module example

### ISSUE THREAD

**Issue by hsnoil** [nextapps-de/mikado#76]
This is actually 3 issues, but they are all related to the same example.

```html
<script>
    import Mikado from "https://unpkg.com/mikado@0.8.3/dist/module/mikado.js";
</script>
```
This doesn't work, the first issue is that it's type is not a module.

If you fix it like so:
```html
<script type="module">
    import Mikado from "https://unpkg.com/mikado@0.8.3/dist/module/mikado.js";
</script>
```
you get into the next issue of it not being on the cdn, because the versions don't match.

If you fix it like so:
```html
<script type="module">
    import Mikado from "https://unpkg.com/mikado@0.8.301/dist/module/mikado.js";
</script>
```

You run into the final issue of:
```
GET https://unpkg.com/mikado@0.8.301/dist/module/profiler.js net::ERR_ABORTED 404 (Not Found)
```
Which is the 3rd issue of profiler.js not being included in dist

**Comment by hsnoil** [comment]
It works so far, thanks!

One thing, looking the cdn supports latest, so that may be easier than constantly updating the version in the readme

```
<script type="module">
    import Mikado from "https://unpkg.com/mikado@latest/dist/module/mikado.js";
</script>
```

**Comment by ts-thomas** [comment]
You are right it would be easier, but also it may break in a future update. From my personal experience I can just suggest to use fixed versions.
