### ISSUE TITLE
script locks up the compiler

### ISSUE THREAD

**Issue by hsnoil** [nextapps-de/mikado#82]
If you run `npx mikado-compile template/app.html --compact --force --module` on the following, the compiler will lock up
```html
<main>
  <section>
<script>{{@ const value = "test"; }}</script>
    <p>{{value}}</p>
  </section>
</main>
```

**Comment by hsnoil** [comment]
Tried it, still causes a lockup :(

**Comment by ts-thomas** [comment]
I found the issue, fix is uploaded to github, I will make a npm release later. Thanks again for this example 👍
