### ISSUE TITLE
The `mouseenter` and `mouseleave` events seems not to work.

### ISSUE THREAD

**Issue by dominikkrulak** [nextapps-de/mikado#84]
Try this on any element in a template: 
```
<div class="w-48 h-48 bg-accent" mouseenter="hover" mouseleave="hover">Test</div>
```
and
```
const view = new Mikado(template, {});

view.route("hover", function(target, event){
  console.log("test");
}, {});

view.mount(document.getElementById('app')).render();
```

**Comment by ts-thomas** [comment]
Both events don't bubble by default. You can alternatively use "mouseover". I will add support for both event types, but it just can bind listener to the element directly, so this isn't efficient as much as global event delegation.

**Comment by ts-thomas** [comment]
@dominikkrulak The latest update has support for non-bubbling events. If you have any issues please open this ticket again. Thanks a lot.
