### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by anthonyivol** [nextapps-de/mikado#9]
Hi, first congrats as it looks like a very promising project ! 

However I had problems while following the basic exemple : 

This work :
`npm install mikado-compile`
`npx mikado-compile template.html`

This doesn't work :
`npm install mikado-compile`
`npx mikado compile template.html`
**Error: Module was not found. Please run 'npm install mikado-compile'**

I also try to install it globally but without success.

using nvm
node version : 8.9.1 and 8.12.0
mac os Mojave

**Comment by anthonyivol** [comment]
Same problem with mikado server : 

This doesn't work :
`npm install mikado-server`
`npx mikado server`
**Error: Module was not found. Please run 'npm install mikado-server'**

And this doesn't (maybe not related):
`npm install mikado-server`
`npx mikado-server`
**/path/to/node_modules/.bin/mikado-server: line 1: syntax error near unexpected token `('**
**/path/to/node_modules/.bin/mikado-server: line 1: `const cluster = require("cluster");**

**Comment by ts-thomas** [comment]
Hello, thanks for the report.

To make "mikado" available you have to also install mikado.
```
npm install mikado
npm install mikado-compile
npx mikado compile template.html
```
This should work. But probably I will remove this and keep just "npx mikado-compile"

**Comment by s0kil** [comment]
What if we just use `npx mikado-compile` inside [cli.js](https://github.com/nextapps-de/mikado/blob/master/task/cli.js) ?

**Comment by anthonyivol** [comment]
> Hello, thanks for the report.
> 
> To make "mikado" available you have to also install mikado.
> 
> ```
> npm install mikado
> npm install mikado-compile
> npx mikado compile template.html
> ```
> 
> This should work. But probably I will remove this and keep just "npx mikado-compile"

Yep, mikado was installed locally, then globally, but without success. Anyway mikado-compile is working... But I agree that it is confusing and perhaps having only one command is better.

**Comment by ts-thomas** [comment]
Will be improved in the upcoming version
